workflows:
  unsigned-ios-ipa:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      xcode: "16.1"  # This version is supported and matches your log
    scripts:
      - name: Install Bun and Dependencies
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          rm -rf node_modules ios android
          bun install
          npm install -g expo-cli

      - name: Expo Prebuild and Pod Install
        script: |
          npx expo prebuild --platform ios --clean || { echo "Prebuild failed!"; exit 1; }
          echo "ios/ contents after prebuild:"
          ls -la ios/
          cd ios || { echo "No ios/ generated!"; exit 1; }
          pod install --repo-update || { echo "Pod install failed!"; exit 1; }
          echo "ios/ after pod install:"
          ls -la
          cd ..

      - name: Build Unsigned Archive and IPA
        script: |
          cd ios
          WORKSPACE_DIR=$(find . -type d -name "*.xcworkspace" -maxdepth 2 | head -n 1 | sed 's|^\./||')
          if [ -z "$WORKSPACE_DIR" ]; then
            echo "ERROR: No .xcworkspace found!"
            ls -la
            exit 1
          fi
          SCHEME=$(basename "$WORKSPACE_DIR" .xcworkspace)
          echo "Found workspace: $WORKSPACE_DIR | Scheme: $SCHEME"
          xcodebuild archive \
            -workspace "$WORKSPACE_DIR" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          cd ..
          echo "Archive contents:"
          ls -la build/GoldPriceCalculator.xcarchive/Products/Applications/ || echo "No .app generated!"
          mkdir -p ipa/Payload
          cp -r build/GoldPriceCalculator.xcarchive/Products/Applications/*.app ipa/Payload/ || { echo "No .app to copy!"; exit 1; }
          echo "Payload contents:"
          ls -la ipa/Payload/
          cd ipa
          zip -r ../unsigned.ipa Payload
          cd ..
          echo "IPA created:"
          ls -lh unsigned.ipa  # Should be 20-100MB

    artifacts:
      - unsigned.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com
