workflows:
  unsigned-ios-ipa:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 90
    environment:
      xcode: "16.1"
    scripts:
      - name: Install Bun and Dependencies
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          rm -rf node_modules ios android
          bun install
          npm install -g expo-cli

      - name: Expo Prebuild and Pod Install
        script: |
          npx expo prebuild --platform ios --clean || { echo "Prebuild failed!"; exit 1; }
          echo "=== FULL ios/ listing after prebuild ==="
          ls -laR ios/   # Recursive to see inside folders
          cd ios || { echo "No ios/ generated!"; exit 1; }
          pod install --repo-update || { echo "Pod install failed!"; exit 1; }
          echo "=== FULL ios/ listing after pod install ==="
          ls -laR .
          cd ..

      - name: Build Unsigned Archive and IPA
        script: |
          cd ios
          # Better detection: find the actual .xcworkspace directory
          WORKSPACE_DIR=$(find . -type d -name "*.xcworkspace" -maxdepth 2 | head -n 1 | sed 's|^\./||')
          if [ -z "$WORKSPACE_DIR" ]; then
            echo "ERROR: No .xcworkspace directory found in ios/!"
            ls -laR .
            exit 1
          fi
          echo "Found workspace directory: $WORKSPACE_DIR"

          # Scheme is usually the basename without .xcworkspace
          SCHEME=$(basename "$WORKSPACE_DIR" .xcworkspace)
          echo "Using scheme: $SCHEME"

          xcodebuild archive \
            -workspace "$WORKSPACE_DIR" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          cd ..
          echo "Archive created? Listing Applications:"
          ls -la build/GoldPriceCalculator.xcarchive/Products/Applications/ || echo "No Applications folder - archive likely empty/failed!"
          mkdir -p ipa/Payload
          cp -r build/GoldPriceCalculator.xcarchive/Products/Applications/*.app ipa/Payload/ 2>/dev/null || { echo "Failed to copy .app - check if it exists above!"; exit 1; }
          echo "Payload after copy:"
          ls -la ipa/Payload/
          cd ipa
          zip -r ../unsigned.ipa Payload
          cd ..
          echo "Final IPA:"
          ls -lh unsigned.ipa

    artifacts:
      - unsigned.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com
